apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-deployment
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb-deployment
    spec:
      containers:
      - image: bitnami/mariadb:10.1
        name: mariadb
        ports:
            - containerPort: 3306
              name: db-port
        env:
            # Database that will be created
            # WordPress must use these credentials
            - name: MARIADB_USER
              value: bn_wordpress
            - name: MARIADB_DATABASE
              value: bitnami_wordpress
            - name: MARIADB_PASSWORD
              value: securepassword123
            - name: MARIADB_ROOT_PASSWORD
              value: moresecurepassword1234
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-deployment
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prestashop-deployment
    spec:
      containers:
      - image: apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prestashop-deployment
  name: prestashop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prestashop-deployment
    spec:
      containers:
      - image: bitnami/prestashop:1.7
        name: prestashop
        ports:
            - containerPort: 3306
              name: db-port
        env:
            - name: MARIADB_USER
              value: bn_wordpress
            - name: MARIADB_DATABASE
              value: bitnami_wordpress
            - name: ALLOW_EMPTY_PASSWORD
              value: yes
