apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-deployment
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb-deployment
    spec:
      containers:
      - image: bitnami/mariadb:10.1
        name: mariadb
        ports:
            - containerPort: 3306
              name: db-port
        env:
            # Database that will be created
            # WordPress must use these credentials
            - name: MARIADB_USER
              value: bn_wordpress
            - name: MARIADB_DATABASE
              value: bitnami_wordpress
            - name: MARIADB_PASSWORD
              value: securepassword123
            - name: MARIADB_ROOT_PASSWORD
              value: moresecurepassword1234
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prestashop-deployment
  name: prestashop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prestashop-deployment
    spec:
      containers:
      - image: bitnami/prestashop:1.7
        name: prestashop
        ports:
            - containerPort: 3306
              name: db-port
        env:
            - name: MARIADB_HOST
              value: mariadb
            - name: MARIADB_PORT_NUMBER
              value: "3306"
            - name: PRESTASHOP_HOST
              value: localhost
            - name: PRESTASHOP_DATABASE_USER
              value: bn_prestashop
            - name: PRESTASHOP_DATABASE_NAME
              value: bitnami_prestashop
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
---
kind: Namespace
apiVersion: v1
metadata:
  name: development
  labels:
    name: development
---
echo 'securepassword123' | base64 ==> c2VjdXJlcGFzc3dvcmQxMjMK
echo 'c2VjdXJlcGFzc3dvcmQxMjMK' | base64 --decode ==> securepassword123
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  MARIADB_PASSWORD: c2VjdXJlcGFzc3dvcmQxMjMK
  MARIADB_ROOT_PASSWORD: bW9yZXNlY3VyZXBhc3N3b3JkMTIzNAo=
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  MARIADB_USER: bn_wordpress
  MARIADB_DATABASE: bitnami_wordpress
  MARIADB_HOST: mariadb
  MARIADB_PORT_NUMBER: "3306"
  PRESTASHOP_HOST: localhost
  PRESTASHOP_DATABASE_USER: bn_prestashop
  PRESTASHOP_DATABASE_NAME: bitnami_prestashop
  ALLOW_EMPTY_PASSWORD: "yes"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-deployment
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb-deployment
    spec:
      containers:
      - image: bitnami/mariadb:10.1
        name: mariadb
        ports:
            - containerPort: 3306
              name: db-port
        env:
            # Database that will be created
            # WordPress must use these credentials
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: MARIADB_USER
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: MARIADB_DATABASE
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MARIADB_PASSWORD
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MARIADB_ROOT_PASSWORD
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prestashop-deployment
  name: prestashop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prestashop-deployment
    spec:
      containers:
      - image: bitnami/prestashop:1.7
        name: prestashop
        ports:
            - containerPort: 3306
              name: db-port
        env:
            - name: MARIADB_HOST
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: MARIADB_HOST
            - name: MARIADB_PORT_NUMBER
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: MARIADB_PORT_NUMBER
            - name: PRESTASHOP_HOST
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: MARIADB_HOST
            - name: PRESTASHOP_DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: PRESTASHOP_HOST
            - name: PRESTASHOP_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: PRESTASHOP_DATABASE_NAME
            - name: ALLOW_EMPTY_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: ALLOW_EMPTY_PASSWORD
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-data-disk
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-deployment
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb-deployment
    spec:
      containers:
      - image: bitnami/mariadb:10.1
        name: mariadb
        ports:
            - containerPort: 3306
              name: db-port
        env:
            # Database that will be created
            # WordPress must use these credentials
            - name: MARIADB_USER
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: MARIADB_USER
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: MARIADB_DATABASE
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MARIADB_PASSWORD
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MARIADB_ROOT_PASSWORD
            volumeMounts:
              - name: mariadb-data
              mountPath: /var/lib/mariadb      
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data-claim 
---
kind: Service
apiVersion: v1
metadata:
  name: database
  creationTimestamp:
  labels:
    service: database
spec:
  ports:
  - name: '3306'
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    service: database
status:
  loadBalancer: {}
---
kind: Service
apiVersion: v1
metadata:
  name: web
  creationTimestamp:
  labels:
    service: web
spec:
  ports:
  - name: '8080'
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    service: web
  type: LoadBalancer
status:
  loadBalancer: {}
